### ISSUE TITLE
[JENKINS-21520] NoClassDefFoundError in git client 1.6.1

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/git-client-plugin#1422]
<p>After update to 1.6.1 I now get the following:</p>

<p>Building on master in workspace /usr/local/NAS/jenkins_jobs/master-Documentation/workspace</p>

<p>Deleting project workspace... done</p>

<p>FATAL: org.jenkinsci.plugins.gitclient.GitClient<br/>
java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient<br/>
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:63)<br/>
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:54)<br/>
	at hudson.FilePath.act(FilePath.java:914)<br/>
	at hudson.FilePath.act(FilePath.java:887)<br/>
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:66)<br/>
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:569)<br/>
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:561)<br/>
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:866)<br/>
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1411)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:651)<br/>
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)<br/>
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:560)<br/>
	at hudson.model.Run.execute(Run.java:1670)<br/>
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)<br/>
	at hudson.model.ResourceController.execute(ResourceController.java:88)<br/>
	at hudson.model.Executor.run(Executor.java:231)</p>

<p>Reverting to 1.6.0 resolves the issue.</p>

---
<details><summary><i>Originally reported by <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/s7726.jpg" title="s7726's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=s7726">s7726</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520" target="_blank">NoClassDefFoundError in git client 1.6.1</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ndeloof.png" title="ndeloof's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof">ndeloof</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>component(s)</b>: git-client-plugin
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2014-07-25T02:03:05+00:00
<li><b>votes</b>: 3
<li><b>watchers</b>: 7
<li><b>imported</b>: 20251211-071809
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>After update to 1.6.1 I now get the following:</p>

<p>Building on master in workspace /usr/local/NAS/jenkins_jobs/master-Documentation/workspace</p>

<p>Deleting project workspace... done</p>

<p>FATAL: org.jenkinsci.plugins.gitclient.GitClient
java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:63)
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:54)
	at hudson.FilePath.act(FilePath.java:914)
	at hudson.FilePath.act(FilePath.java:887)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:66)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:569)
	at hudson.plugins.git.GitSCM.createClient(GitSCM.java:561)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:866)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1411)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:651)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:88)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:560)
	at hudson.model.Run.execute(Run.java:1670)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:231)</p>

<p>Reverting to 1.6.0 resolves the issue.</p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Linux, Jenkins</code></li></ul>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=195068&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195068">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The related bug report has been closed as a configuration error.  Have you found a configuration related solution to this problem as well?</p>

<p>If not, can you provide more details about the configuration you're running?  Have you installed the latest version of the plugins (including credentials)?  Are any of your plugins disabled?  Are any of your plugins pinned to older versions?</p>
</pre>
</details>

</ul>
</details>

<p>The related bug report has been closed as a configuration error.  Have you found a configuration related solution to this problem as well?</p>

<p>If not, can you provide more details about the configuration you're running?  Have you installed the latest version of the plugins (including credentials)?  Are any of your plugins disabled?  Are any of your plugins pinned to older versions?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>postalservice14:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=195141&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195141">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Weird, I'm getting this error on 1.6.2, but reverting to 1.6.1 fixes it for me.</p>

<p>My credentials plugin is installed and enabled, but I'm not using it.</p>
</pre>
</details>

</ul>
</details>

<p>Weird, I'm getting this error on 1.6.2, but reverting to 1.6.1 fixes it for me.</p>

<p>My credentials plugin is installed and enabled, but I'm not using it.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=195146&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-195146">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>That's bad news.  I'm not aware of any changes which should have altered the class loading.</p>

<p>What version of Jenkins are you running?  I'm currently using 1.532.2 (the long term support release) and have not done any experiments with the new versions (like 1.551).</p>
</pre>
</details>

</ul>
</details>

<p>That's bad news.  I'm not aware of any changes which should have altered the class loading.</p>

<p>What version of Jenkins are you running?  I'm currently using 1.532.2 (the long term support release) and have not done any experiments with the new versions (like 1.551).</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/rsandell.png" title="rsandell's avatar" /> rsandell:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=198220&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-198220">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Reverting to 1.6.1 fixed it for us as well, for a while. Then it happened again, in runtime, without a restart.
We are also running 1.532.2 with all plugins updated to the latest version at the time of upgrade (so credentials plugin is in there as well).</p>
</pre>
</details>

</ul>
</details>

<p>Reverting to 1.6.1 fixed it for us as well, for a while. Then it happened again, in runtime, without a restart.<br/>
We are also running 1.532.2 with all plugins updated to the latest version at the time of upgrade (so credentials plugin is in there as well).</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=201529&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-201529">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>A <a href="https://issues.jenkins-ci.org/browse/JENKINS-20254?focusedCommentId=199584&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199584" class="external-link" target="_blank" rel="nofollow noopener">comment</a> in <a href="https://issues.jenkins.io/browse/JENKINS-20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="JENKINS-20254"><del>JENKINS-20254</del></a> indicates that the ssh-credentials plugin must also be enabled.  Could you double check that your ssh-credentials plugin is enabled on the failing configuration?</p>
</pre>
</details>

</ul>
</details>

<p>A <a href="https://issues.jenkins-ci.org/browse/JENKINS-20254?focusedCommentId=199584&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-199584" class="external-link" target="_blank" rel="nofollow noopener">comment</a> in <a href="https://issue-redirect.jenkins.io/issue/20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/20254">JENKINS-20254</a>"><del>JENKINS-20254</del></a> indicates that the ssh-credentials plugin must also be enabled.  Could you double check that your ssh-credentials plugin is enabled on the failing configuration?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=206435&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-206435">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>I'm unable to duplicate this bug, nor do there seem to be ongoing reports of the problem.  Closing it as "Cannot reproduce".</p>
</pre>
</details>

</ul>
</details>

<p>I'm unable to duplicate this bug, nor do there seem to be ongoing reports of the problem.  Closing it as "Cannot reproduce".</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231822&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231822">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Nicolas De Loof
Path:
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
<a href="http://jenkins-ci.org/commit/git-client-plugin/03409a462896c5c5cd118a88a9e4718c39f605df" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/03409a462896c5c5cd118a88a9e4718c39f605df</a>
Log:
  <a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Nicolas De Loof<br/>
Path:<br/>
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java<br/>
<a href="http://jenkins-ci.org/commit/git-client-plugin/03409a462896c5c5cd118a88a9e4718c39f605df" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/03409a462896c5c5cd118a88a9e4718c39f605df</a><br/>
Log:<br/>
  <a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231825&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231825">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Nicolas De Loof
Path:
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
<a href="http://jenkins-ci.org/commit/git-client-plugin/f7e7c19b8bdf4080bcf6034818e2736c1fd09b18" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/f7e7c19b8bdf4080bcf6034818e2736c1fd09b18</a>
Log:
  <a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Nicolas De Loof<br/>
Path:<br/>
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java<br/>
<a href="http://jenkins-ci.org/commit/git-client-plugin/f7e7c19b8bdf4080bcf6034818e2736c1fd09b18" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/f7e7c19b8bdf4080bcf6034818e2736c1fd09b18</a><br/>
Log:<br/>
  <a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231826&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231826">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Nicolas De Loof
Path:
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
<a href="http://jenkins-ci.org/commit/git-client-plugin/fc708cf66cf4a432b9e4a215c24fc3befb23e6b6" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/fc708cf66cf4a432b9e4a215c24fc3befb23e6b6</a>
Log:
  <a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Nicolas De Loof<br/>
Path:<br/>
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java<br/>
<a href="http://jenkins-ci.org/commit/git-client-plugin/fc708cf66cf4a432b9e4a215c24fc3befb23e6b6" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/fc708cf66cf4a432b9e4a215c24fc3befb23e6b6</a><br/>
Log:<br/>
  <a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231898&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231898">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Nicolas De Loof
Path:
 src/main/java/hudson/plugins/git/GitTool.java
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
<a href="http://jenkins-ci.org/commit/git-client-plugin/377561efbb3263c05058ab15ffd8cadbaba4dc56" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/377561efbb3263c05058ab15ffd8cadbaba4dc56</a>
Log:
  <a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Nicolas De Loof<br/>
Path:<br/>
 src/main/java/hudson/plugins/git/GitTool.java<br/>
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java<br/>
<a href="http://jenkins-ci.org/commit/git-client-plugin/377561efbb3263c05058ab15ffd8cadbaba4dc56" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/377561efbb3263c05058ab15ffd8cadbaba4dc56</a><br/>
Log:<br/>
  <a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231899&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231899">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Mark Waite
Path:
 src/main/java/hudson/plugins/git/GitTool.java
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java
<a href="http://jenkins-ci.org/commit/git-client-plugin/0b57fecc2bb9c6aa2087f5aceaf82326b62b5859" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/0b57fecc2bb9c6aa2087f5aceaf82326b62b5859</a>
Log:
  Merge pull request #171 from ndeloof/master</p>

<p><a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


<p>Compare: <a href="https://github.com/jenkinsci/git-client-plugin/compare/886a32277375...0b57fecc2bb9" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/git-client-plugin/compare/886a32277375...0b57fecc2bb9</a></p>

</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Mark Waite<br/>
Path:<br/>
 src/main/java/hudson/plugins/git/GitTool.java<br/>
 src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java<br/>
<a href="http://jenkins-ci.org/commit/git-client-plugin/0b57fecc2bb9c6aa2087f5aceaf82326b62b5859" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-client-plugin/0b57fecc2bb9c6aa2087f5aceaf82326b62b5859</a><br/>
Log:<br/>
  Merge pull request #171 from ndeloof/master</p>

<p><a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a> transient NoClassDefFoundError: javax/servlet/ServletException</p>


<p>Compare: <a href="https://github.com/jenkinsci/git-client-plugin/compare/886a32277375...0b57fecc2bb9" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/jenkinsci/git-client-plugin/compare/886a32277375...0b57fecc2bb9</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/scm_issue_link.png" title="scm_issue_link's avatar" /> scm_issue_link:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=231925&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-231925">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Code changed in jenkins
User: Mark Waite
Path:
 src/main/java/hudson/plugins/git/util/BuildData.java
 src/test/java/hudson/plugins/git/AbstractGitRepository.java
 src/test/java/hudson/plugins/git/AbstractGitTestCase.java
 src/test/java/hudson/plugins/git/GitPublisherTest.java
 src/test/java/hudson/plugins/git/SCMTriggerTest.java
<a href="http://jenkins-ci.org/commit/git-plugin/9369a12c7bc4cdee6cea399029f302533727595a" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-plugin/9369a12c7bc4cdee6cea399029f302533727595a</a>
Log:
  Inline references to hudson.Functions, trying to resolve <a href="https://issues.jenkins.io/browse/JENKINS-21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="JENKINS-21520"><del>JENKINS-21520</del></a></p>


</pre>
</details>

</ul>
</details>

<p>Code changed in jenkins<br/>
User: Mark Waite<br/>
Path:<br/>
 src/main/java/hudson/plugins/git/util/BuildData.java<br/>
 src/test/java/hudson/plugins/git/AbstractGitRepository.java<br/>
 src/test/java/hudson/plugins/git/AbstractGitTestCase.java<br/>
 src/test/java/hudson/plugins/git/GitPublisherTest.java<br/>
 src/test/java/hudson/plugins/git/SCMTriggerTest.java<br/>
<a href="http://jenkins-ci.org/commit/git-plugin/9369a12c7bc4cdee6cea399029f302533727595a" class="external-link" target="_blank" rel="nofollow noopener">http://jenkins-ci.org/commit/git-plugin/9369a12c7bc4cdee6cea399029f302533727595a</a><br/>
Log:<br/>
  Inline references to hudson.Functions, trying to resolve <a href="https://issue-redirect.jenkins.io/issue/21520" title="NoClassDefFoundError in git client 1.6.1" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/21520">JENKINS-21520</a>"><del>JENKINS-21520</del></a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=232504&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-232504">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The referenced git plugin changes are included in 2.4.0 which was released 18 Jul 2015.</p>

<p>The referenced git client plugin changes are included in 1.18.0 which was released 18 Jul 2015.</p>

<p>The root problem is not fixed by those changes and it is not clear if the referenced changes will be sufficient to resolve the issue.  They did resolve the issue for <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof" class="user-hover" rel="ndeloof">ndeloof</a></p>
</pre>
</details>

</ul>
</details>

<p>The referenced git plugin changes are included in 2.4.0 which was released 18 Jul 2015.</p>

<p>The referenced git client plugin changes are included in 1.18.0 which was released 18 Jul 2015.</p>

<p>The root problem is not fixed by those changes and it is not clear if the referenced changes will be sufficient to resolve the issue.  They did resolve the issue for <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof" class="user-hover" rel="ndeloof">ndeloof</a></p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/jglick.png" title="jglick's avatar" /> jglick:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-21520?focusedId=234238&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-234238">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The general bug is in core, that there should be a blacklist of classes which should never be sent over a slave remoting channel. Cannot remember if that is filed or not.</p>
</pre>
</details>

</ul>
</details>

<p>The general bug is in core, that there should be a blacklist of classes which should never be sent over a slave remoting channel. Cannot remember if that is filed or not.</p>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `is_duplicated_by` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/22098">JENKINS-22098</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/29647">JENKINS-29647</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/21745">JENKINS-21745</a>]</i>

**Comment by jenkins-infra-bot** [comment]
<i>[Original `relates_to` from Jira: <a class="jira-relationship" href="https://issue-redirect.jenkins.io/issue/29278">JENKINS-29278</a>]</i>
