### ISSUE TITLE
[JENKINS-25351] NoClassDefFoundError: ... GitClient: pasting a repository URL

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/git-client-plugin#1457]
<p>Hi ,<br/>
I am getting below excpetion while copying git url on "Repository URL", it throws below excpetions and stacktrace.</p>

<p>jenkins having below plugins related to git and credentials and enabled.<br/>
Jenkins core-  1.532.2<br/>
credential- 1.10 enabled<br/>
ssh-credential- 1.6.1 enabled<br/>
git- 2.2.1 enabled<br/>
git-client- 1.9.0 enabled<br/>
git-server- 1.3 enabled</p>

<p>permission- anonymous user not having any(read/write)permission due to security </p>

<p>Stack trace</p>

```
javax.servlet.ServletException: java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:90)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:174)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ApiTokenFilter.doFilter(ApiTokenFilter.java:79)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:63)
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:54)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:66)
	at hudson.plugins.git.UserRemoteConfig$DescriptorImpl.doCheckUrl(UserRemoteConfig.java:147)
	at sun.reflect.GeneratedMethodAccessor1433.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:120)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	... 67 more

```

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=hiteswar_kumar">hiteswar_kumar</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25351" target="_blank">NoClassDefFoundError: ... GitClient: pasting a repository URL</a></i></summary>
<i><ul>
<li><b>assignee</b>: <img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/ndeloof.png" title="ndeloof's avatar" /> <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=ndeloof">ndeloof</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>component(s)</b>: git-client-plugin
<li><b>resolution</b>: Cannot Reproduce
<li><b>resolved</b>: 2014-11-26T16:02:48+00:00
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 20251211-071809
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>Hi ,
I am getting below excpetion while copying git url on "Repository URL", it throws below excpetions and stacktrace.</p>

<p>jenkins having below plugins related to git and credentials and enabled.
Jenkins core-  1.532.2
credential- 1.10 enabled
ssh-credential- 1.6.1 enabled
git- 2.2.1 enabled
git-client- 1.9.0 enabled
git-server- 1.3 enabled</p>

<p>permission- anonymous user not having any(read/write)permission due to security </p>

<p>Stack trace</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>javax.servlet.ServletException: java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:723)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:202)
	at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:180)
	at net.bull.javamelody.PluginMonitoringFilter.doFilter(PluginMonitoringFilter.java:85)
	at org.jvnet.hudson.plugins.monitoring.HudsonMonitoringFilter.doFilter(HudsonMonitoringFilter.java:90)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:174)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ApiTokenFilter.doFilter(ApiTokenFilter.java:79)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:470)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:861)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:606)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoClassDefFoundError: org.jenkinsci.plugins.gitclient.GitClient
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:63)
	at org.jenkinsci.plugins.gitclient.Git$1.invoke(Git.java:54)
	at org.jenkinsci.plugins.gitclient.Git.getClient(Git.java:66)
	at hudson.plugins.git.UserRemoteConfig$DescriptorImpl.doCheckUrl(UserRemoteConfig.java:147)
	at sun.reflect.GeneratedMethodAccessor1433.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:120)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
	... 67 more
</pre>
</div></div></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Jenkins core-  1.532.2<br/>
credential- 1.10 enabled<br/>
ssh-credential- 1.6.1 enabled<br/>
git- 2.2.1 enabled<br/>
git-client- 1.9.0 enabled<br/>
git-server- 1.3 enabled<br/>
```
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25351?focusedId=214956&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-214956">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>You list that the various plugins are enabled, yet <a href="https://issues.jenkins.io/browse/JENKINS-20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="JENKINS-20254"><del>JENKINS-20254</del></a> suggests that one possible cause of that is a disabled dependent plugin. Do you have any plugins disabled?</p>

<p>Have you restarted Jenkins after enabling plugins?</p>

<p>Can you see the same failure with recent versions of the plugins (like git plugin 2.2.7, git-client plugin 1.11.0, git-server 1.4, and the latest versions of the other plugins as well)?</p>

<p>What Java version are you running, and on what operating system?</p>
</pre>
</details>

</ul>
</details>

<p>You list that the various plugins are enabled, yet <a href="https://issue-redirect.jenkins.io/issue/20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/20254">JENKINS-20254</a>"><del>JENKINS-20254</del></a> suggests that one possible cause of that is a disabled dependent plugin. Do you have any plugins disabled?</p>

<p>Have you restarted Jenkins after enabling plugins?</p>

<p>Can you see the same failure with recent versions of the plugins (like git plugin 2.2.7, git-client plugin 1.11.0, git-server 1.4, and the latest versions of the other plugins as well)?</p>

<p>What Java version are you running, and on what operating system?</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>hiteswar_kumar:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25351?focusedId=214965&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-214965">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Hi Mark,
Thanks for your comment and check.
please find my comments inline.</p>

<p>&gt;&gt;Do you have any plugins disabled?
#there is no disabled plugin on Jenkins environment .
and the git-client's dependent plugin "ssh-credential" is already enabled as shared.
do you see any other plugin to check.</p>

<p>&gt;&gt;Have you restarted Jenkins after enabling plugins?
#issue started after upgrading build failure analysis "build-failure-analyzer 1.10.3 from 1.7.0 t" and restarting of jenkins .
issue was no available before that.</p>

<p>&gt;&gt;Can you see the same failure with recent versions of the plugins (like git plugin 2.2.7, git-client plugin 1.11.0, git-server 1.4, and the latest versions of the other plugins as well)?
#we have another jenkins master of same version of plugins(ssh-credential- 1.6.1 enabled,git- 2.2.1 enabled,git-client- 1.9.0 enabled) and core.
but this issue is not appeared at another jenkins master.</p>

<p>&gt;&gt;What Java version are you running, and on what operating system?</p>
<ol>
	<li>java version "1.6.0_27" at both Jenkins masters on 12.04 ubuntu OS.</li>
</ol>

</pre>
</details>

</ul>
</details>

<p>Hi Mark,<br/>
Thanks for your comment and check.<br/>
please find my comments inline.</p>

<p>>>Do you have any plugins disabled?<br/>
#there is no disabled plugin on Jenkins environment .<br/>
and the git-client's dependent plugin "ssh-credential" is already enabled as shared.<br/>
do you see any other plugin to check.</p>

<p>>>Have you restarted Jenkins after enabling plugins?<br/>
#issue started after upgrading build failure analysis "build-failure-analyzer 1.10.3 from 1.7.0 t" and restarting of jenkins .<br/>
issue was no available before that.</p>

<p>>>Can you see the same failure with recent versions of the plugins (like git plugin 2.2.7, git-client plugin 1.11.0, git-server 1.4, and the latest versions of the other plugins as well)?<br/>
#we have another jenkins master of same version of plugins(ssh-credential- 1.6.1 enabled,git- 2.2.1 enabled,git-client- 1.9.0 enabled) and core.<br/>
but this issue is not appeared at another jenkins master.</p>

<p>>>What Java version are you running, and on what operating system?</p>
<ol>
	<li>java version "1.6.0_27" at both Jenkins masters on 12.04 ubuntu OS.</li>
</ol>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25351?focusedId=214966&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-214966">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The NoClassDefFoundError is not repeatable (as far as I can tell), based on <a href="https://issues.jenkins.io/browse/JENKINS-20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="JENKINS-20254"><del>JENKINS-20254</del></a> and one or more other bug reports like it. Eventually it seemed that enabling all plugins was sufficient to fix the problem. However, I am not certain that is actually what fixed the problem. Users may have updated to more recent versions of the plugins, and thus fixed the problem without realizing that their upgrade process also fixed the issue.</p>

<p>Your plugin versions seem to be out of date, and your Java version is out of date. Unfortunately, I don't think the Java version is the root of this problem. I suspect it may be the plugin versions you're running, and some difference in the installed or enabled plugins between your two locations.</p>

<p>You might compare the Jenkins configurations of the two installations, to see if there are any differences which help you to understand the root of the problem.</p>
</pre>
</details>

</ul>
</details>

<p>The NoClassDefFoundError is not repeatable (as far as I can tell), based on <a href="https://issue-redirect.jenkins.io/issue/20254" title="NoClassDefFoundError adding HTTPS URL for Git repository - fails" class="issue-link" data-issue-key="<a class="jira-plain-text-key" href="https://issue-redirect.jenkins.io/issue/20254">JENKINS-20254</a>"><del>JENKINS-20254</del></a> and one or more other bug reports like it. Eventually it seemed that enabling all plugins was sufficient to fix the problem. However, I am not certain that is actually what fixed the problem. Users may have updated to more recent versions of the plugins, and thus fixed the problem without realizing that their upgrade process also fixed the issue.</p>

<p>Your plugin versions seem to be out of date, and your Java version is out of date. Unfortunately, I don't think the Java version is the root of this problem. I suspect it may be the plugin versions you're running, and some difference in the installed or enabled plugins between your two locations.</p>

<p>You might compare the Jenkins configurations of the two installations, to see if there are any differences which help you to understand the root of the problem.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i><img align="left" width="20" src="https://raw.githubusercontent.com/jenkinsci/artifacts-from-jira-issues/refs/heads/main/avatars/markewaite.png" title="markewaite's avatar" /> markewaite:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-25351?focusedId=216940&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-216940">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Cannot reproduce the bug.</p>
</pre>
</details>

</ul>
</details>

<p>Cannot reproduce the bug.</p>
